/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExamsCbtRouteImport } from './routes/exams/cbt'

const ExamsCbtRoute = ExamsCbtRouteImport.update({
  id: '/exams/cbt',
  path: '/exams/cbt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/exams/cbt': typeof ExamsCbtRoute
}
export interface FileRoutesByTo {
  '/exams/cbt': typeof ExamsCbtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/exams/cbt': typeof ExamsCbtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/exams/cbt'
  fileRoutesByTo: FileRoutesByTo
  to: '/exams/cbt'
  id: '__root__' | '/exams/cbt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExamsCbtRoute: typeof ExamsCbtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/exams/cbt': {
      id: '/exams/cbt'
      path: '/exams/cbt'
      fullPath: '/exams/cbt'
      preLoaderRoute: typeof ExamsCbtRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ExamsCbtRoute: ExamsCbtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
